#!/usr/bin/env bash
set -euo pipefail

# update system environment after every start
DEBIAN_FRONTEND=noninteractive apt-get update \
                            && apt-get dist-upgrade -y \
                            && apt-get autoremove --purge -y \
                            && apt-get autoclean

# SSL active [APACHE_SSL_ENABLE = true] ?!
if [ "${APACHE_SSL_ENABLE}" = "true" ]; then
  sed -sie "s|SSLCertificateFile.*|SSLCertificateFile ${APACHE_SSL_CERTFILE}|g" \
    "${APACHE_CONFDIR}/sites-available/default-ssl.conf"
  sed -sie "s|SSLCertificateKeyFile.*|SSLCertificateKeyFile ${APACHE_SSL_KEYFILE}|g" \
    "${APACHE_CONFDIR}/sites-available/default-ssl.conf"
  a2enmod ssl >/dev/null
  a2ensite default-ssl >/dev/null
fi

# Run original entrypoint.
exec docker-php-entrypoint apache2-foreground
