#!/usr/bin/env bash
set -euo pipefail

# update system environment after every start
DEBIAN_FRONTEND=noninteractive apt-get update \
                            && apt-get dist-upgrade -y \
                            && apt-get autoremove --purge -y \
                            && apt-get autoclean

# Run original entrypoint.
exec docker-php-entrypoint apache2-foreground
